TaskManager/urls.py
from django.contrib import admin
import debug_toolbar
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include(debug_toolbar.urls)),
    path(
        "taskmanager/",
        include(
            [
                path("schedules/", include("schedules.urls", namespace="schedules")),
                path("tasks/", include("taskEvents.urls", namespace="tasks")),
                path("dashboard/", include("dashboard.urls", namespace="dashboard")),
                path("reviews/", include("reviews.urls", namespace="reviews")),
                path("employees/", include("employees.urls", namespace="employees")),
                path("events/", include("events.urls", namespace="events")),
            ]
        ),
    ),
]

events/urls.py
from django.urls import path
from events import views
from events.views import *

app_name = "events"
urlpatterns = [
    path("", views.calendar_view, name='index'),
    path("<day__gte>", views.calendar_view),
    path("list/", EventListView.as_view(), name='list'),
    path("form/", EventFormView.as_view(), name='form'),
    path("create/", EventCreateView.as_view(), name='create'),
    path("update/<int:pk>", EventUpdateView.as_view(), name='update'),
    path("update-event/<int:pk>", views.update_event, name='change'),
    path("delete/<int:pk>", views.delete_event, name='delete'),
]

events/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.exceptions import ValidationError
from django.urls import reverse
from employees.models import Employees
from datetime import date
from django.utils import timezone


# Create your models here.

class Events(models.Model):
    title = models.CharField(max_length=30)
    notes = models.TextField(
        'Details', blank=True, null=True)
    day = models.DateField('Day of Event')
    start_time = models.TimeField('Begins', default=timezone.now)
    end_time = models.TimeField('Ends', default=timezone.now)

    class Meta:
        verbose_name = 'Event'
        verbose_name_plural = 'Event'

    def check_overlap(self, fixed_start, fixed_end, new_start, new_end):
        overlap = False
        if new_start == fixed_end or new_end == fixed_start:  # edge case
            overlap = False
        elif (new_start >= fixed_start and new_start <= fixed_end) or (new_end >= fixed_start and new_end <= fixed_end):  # innner limits
            overlap = True
        elif new_start <= fixed_start and new_end >= fixed_end:  # outter limits
            overlap = True

        return overlap


    def get_absolute_url(self):
        url = ('update/%s' % (
            self.id))
        return u'<a href="%s">%s</a>' % (url, str(self.title))

    def clean(self):
        if self.end_time <= self.start_time:
            raise ValidationError('Ending times must end after starting times')

        events = Events.objects.filter(day=self.day)
        """Could not prevent validation from preventing update"""
        # if events.exists():
            # for event in events:
            #     if self.check_overlap(event.start_time, event.end_time, self.start_time, self.end_time):
            #         raise ValidationError(
            #             'There is an overlap with another event: ' + str(event.day) + ', ' + str(
            #                 event.title) + ':' + str(event.start_time) + '-' + str(event.end_time))

events/forms.py
from django.forms import ModelForm
from events.models import Events


class EventForm(ModelForm):
    class Meta:
        model = Events
        fields = '__all__'

events/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
import datetime
import calendar
from django.utils.safestring import mark_safe
from django.views.generic.edit import CreateView, UpdateView, FormView
from django.views.generic import ListView
from events.models import Events
from .utils import EventCalendar
from events.forms import EventForm
from django.contrib import messages

# Depricated for EventsCalendar
# from calendar import HTMLCalendar

class EventListView(ListView):
    model = Events

class EventFormView(FormView):
    form_class = EventForm
    template_name = 'events/events_form.html'
    success_url = '/taskmanager/events/'

class EventCreateView(CreateView):
    model = Events
    fields = '__all__'
    success_url="/taskmanager/events/list/"

class EventUpdateView(UpdateView):
    model = Events
    fields = '__all__'

def update_event(request, pk):
    event = Events.objects.get(pk=pk)
    eventForm = EventForm(request.POST)
    initialData = {
        'title': event.title,
        'notes': event.notes,
        'day': event.day,
        'start_time': event.start_time,
        'end_time': event.end_time,
    }
    checkForChange = EventForm(request.POST, initial=initialData)
    if eventForm.is_valid() and checkForChange.has_changed():
        """
        try:
            eventForm.is_valid()
        except ValidationError as e:
            # Do something based on the errors contained in e.message_dict.
            # Display them to a user, or handle them programmatically.
        pass
Model.clean_fields(exclude=None)¶
This method will validate all fields on your model. The optional exclude argument 
lets you provide a list of field names to exclude from validation. It will raise a
ValidationError if any fields fail validation.
        """
        editEvent = EventForm(request.POST, instance=event)
        editEvent.save()
        messages.success(request, "Succesfully Updated Event")
        return redirect("events:list")
    elif not checkForChange.has_changed():
        messages.error(request, "No Event Data Changed")
        context = { "form": eventForm }
        return render(request, 'events/events_form.html', context)
    else:
        messages.error(request, "New Event Details Not Valid")
        context = { "form": eventForm }
        return render(request, 'events/events_form.html', context)

def delete_event(request, pk):
    e = Events.objects.get(pk=pk)
    e.delete()
    return redirect("events:list")

def calendar_view(request, extra_context=None):
    after_day = request.GET.get('day__gte', None)
    extra_context = extra_context or {}

    if not after_day:
        d = datetime.date.today()
    else:
        try:
            split_after_day = after_day.split('-')
            d = datetime.date(year=int(split_after_day[0]), month=int(
                split_after_day[1]), day=1)
        except:
            d = datetime.date.today()

    # find first day of current month
    previous_month = datetime.date(year=d.year, month=d.month, day=1)
    previous_month = previous_month - \
        datetime.timedelta(days=1)  # backs up a single day
    # find first day of previous month
    previous_month = datetime.date(
        year=previous_month.year, month=previous_month.month, day=1)

    last_day = calendar.monthrange(d.year, d.month)
    # find last day of current month
    next_month = datetime.date(year=d.year, month=d.month, day=last_day[1])
    next_month = next_month + \
        datetime.timedelta(days=1)  # forward a single day
    # find first day of next month
    next_month = datetime.date(
        year=next_month.year, month=next_month.month, day=1)

    extra_context['previous_month'] = "/taskmanager/events/" + '?day__gte=' + str(
        previous_month)
    extra_context['next_month'] = "/taskmanager/events/" + \
        '?day__gte=' + str(next_month)

    cal = EventCalendar()
    # cal = HTMLCalendar()
    html_calendar = cal.formatmonth(d.year, d.month, withyear=True)
    html_calendar = html_calendar.replace(
        '<td ', '<td  width="150" height="80" id="cal_cell"')
    extra_context['calendar'] = mark_safe(html_calendar)

    return render(request, 'events/base_calendar.html', extra_context)

events/templates/events/base_calendar.html
{% extends 'dashboard/base.html' %}
{% block title%}Calendar Home{% endblock %}
{% load static %}
{% block styling %}
<link rel="stylesheet" href="{% static 'events/css/events.css' %}" type="text/css" media="screen">
<!-- <script src="{% static 'events/calendar.js' %}" type="text/javascript"></script> -->
{% endblock %}
{% block content %}
    <div class="tab-box">
        <a href={{ previous_month }} class="prev_tab" id="prev_month">
            Previous month
        </a>
        <a href={{ next_month }} class="next_tab" id="next_month">
            Next month
        </a>
    </div>
{{ calendar }}
{% endblock %}

events/templates/events/events_form.html
{% extends 'dashboard/base.html' %}
{% block title%}Events{% endblock %}
{% load static %}
{% block styling %}
<link rel="stylesheet" href="{% static 'events/css/eventsList.css' %}" type="text/css" media="screen">
<script src="{% static 'events/js/eventsList.js' %}" type="text/javascript"></script>
{% endblock %}
{% block content %}
{% if events.id %}
<h3 class="section_title">Update Calendar Event</h3>
{% else %}
<h3 class="section_title">Create Calendar Event</h3>
{% endif %}
<div class="content">
    <div class="form">
        {% if events.id %}
            <form class="eventForm" method="POST" action="{% url 'events:change' events.id %}">{% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-success" type="submit">Update</button>
                <a href="{% url 'events:delete' events.id %}" class="btn btn-warning">Delete</a>
                </form>
            </form>
        {% else %}
            <form class="eventForm" action="{% url 'events:create' %}" method="POST">{% csrf_token %}
                {{ form.as_p }}
                <input class="btn btn-success" type="submit" value="Create">
            </form>
        {% endif %}
    </div>
</div>
{% endblock %}

events/templates/events/events_list.html
{% extends 'dashboard/base.html' %}
{% block title%}Event View{% endblock %}
{% load static %}
{% block styling %}
{% endblock %}
{% block content %}
<h3 class="section_title">Events List</h3> 
<div class="content">
    {% if object_list %}
    <table id="events-table">
        <thead>
            <th>Title</th>
            <th>Notes</th>
            <th>Day</th>
            <th>Start</th>
            <th>End</th>
            <th>Actions</th>
        </thead>
        {% for event in object_list %}
        <tr>
            <td>{{ event.title }}</td>
            <td>{{ event.notes }}</td>
            <td>{{ event.day }}</td>
            <td>{{ event.start_time }}</td>
            <td>{{ event.end_time }}</td>
            <td><a href="{% url 'events:update' event.id %}">Update</a>&nbsp|&nbsp
                <a href="{% url 'events:delete' event.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>
    {% else %}
        <h1>No Events to View</h1>
        <a href="{% url 'events:create' %}" class="btn btn-primary">Create An Event</a>
    {% endif %}
</div>
{% endblock %}