TaskManager/urls.py
from django.contrib import admin
import debug_toolbar
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include(debug_toolbar.urls)),
    path(
        "taskmanager/",
        include(
            [
                path("schedules/", include("schedules.urls", namespace="schedules")),
                path("tasks/", include("taskEvents.urls", namespace="tasks")),
                path("dashboard/", include("dashboard.urls", namespace="dashboard")),
                path("reviews/", include("reviews.urls", namespace="reviews")),
                path("employees/", include("employees.urls", namespace="employees")),
                path("events/", include("events.urls", namespace="events")),
            ]
        ),
    ),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"
urlpatterns = [
    path("", views.index, name="index"),
]

events/urls.py
from django.urls import path
from events import views
from events.views import *

app_name = "events"
urlpatterns = [
    path("", views.calendar_view, name='index'),
    path("<day__gte>", views.calendar_view),
    path("list/", EventListView.as_view(), name='list'),
    path("form/", EventFormView.as_view(), name='form'),
    path("create/", EventCreateView.as_view(), name='create'),
    path("update/<int:pk>", EventUpdateView.as_view(), name='update'),
    path("update-event/<int:pk>", views.update_event, name='change'),
    path("delete/<int:pk>", views.delete_event, name='delete'),
]

taskEvents/urls.py
from django.urls import path
from . import views
from taskEvents.views import *

app_name = "taskEvents"
urlpatterns = [
    path("list/", TaskListView.as_view(), name = 'list'),
    path("create/", TaskCreateView.as_view(), name = 'create'),
    path("update/<int:pk>", TaskUpdateView.as_view(), name = 'update'),
    path("delete/<int:pk>", views.delete_task, name = 'delete'),
    path("select/", views.task_select, name = 'select'),
]

dashboard/views.py
from django.shortcuts import render

# Create your views here.


def index(request):

    return render(request, "dashboard/base_dashboard.html")

dashboard/templates/dashboard/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link
      rel="stylesheet"
      href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <title>{% block title %}TaskManager Home{% endblock %}</title>
    {% load static %}
    {% block styling %}{% endblock %}
    <link rel="stylesheet" href="{% static 'dashboard/css/main.css' %}" type="text/css" media="screen"/>
  </head>
  <body class="container">
    <section class="section-tabs">
      <div class="dropdown">
        <button class="dropbtn tab">Manage Tasks</button>
        <div class="dropdown-content">
          <a href="{% url 'taskEvents:create' %}">Create Tasks</a>
          <a href="{% url 'taskEvents:list' %}">View Tasks</a>
        </div>
      </div>
      <div class="dropdown">
        <button class="dropbtn tab">Employee Data</button>
        <div class="dropdown-content">
          <a href="{% url 'employees:form' %}">Create Employees</a>
          <a href="{% url 'employees:list' %}">View Employees</a>
        </div>
      </div>
      <div class="dropdown">
        <button class="dropbtn tab">Staff Evaluations</button>
        <div class="dropdown-content">
          <a href="{% url 'reviews:create' %}">Create Review</a>
          <a href="{% url 'reviews:index' %}">See Reviews</a>
          <!-- <a href="{% url 'reviews:update' %}">Edit Reviews</a> -->
        </div>
      </div>
      <div class="dropdown">
        <button class="dropbtn tab">Calendar Events</button>
        <div class="dropdown-content">
          <a href="{% url 'events:form' %}">Create Events</a>
          <a href="{% url 'events:index' %}">View Calendar</a>
          <a href="{% url 'events:list' %}">List Events</a>
        </div>
      </div>
      <div class="dropdown">
        <button class="dropbtn tab">Schedules</button>
        <div class="dropdown-content">
          <a href="">Create Schedules</a>
          <a href="{% url 'schedules:list' %}">View Schedules</a>
        </div>
      </div>
    </section>
    <section class="employee-id">
      <div class="emp-img">
        <div id="img">Img</div>
        <a href="" id="change-img">Change Image</a>
      </div>
      <div class="emp-name">
        <h2>Employee Name</h2>
        <button type="submit" action="#" class="btn btn-primary">Logout</button>
      </div>
    </section>
    <section class="qotd">
      <h2>Today's Inspiration</h2>
      <h3>{{ quote.text }}</h3>
      <p>{{ quote.author }}</p>
    </section>
    <section class="schedule-table">
      <h2>Today's Schedule</h2>
      <table>
        <tr>
          <th>In</th>
          <th>Out</th>
          <th>Name</th>
          <th>Role</th>
        </tr>
        <tr>
          <td>5:00</td>
          <td>5:00</td>
          <td>Joaquin Pheonix</td>
          <td>Role</td>
        </tr>
      </table>
    </section>
    <main>
      <div class="messages">
        {% if messages %}
            {% for message in messages %}
                <h3 {% if message.tags %} class="response-msg" id="{{ message.tags }}"{% endif %}>{{ message }}</h3>
            {% endfor %}
        {% endif %}
      </div>
      {% block content%}{% endblock %}
    </main>
    <section class="task-list">
      <h2>Today's Assignments</h2>
    </section>
    <section class="weekly-todo">
      <h3 class="day">Sunday</h3>
      <h3 class="day">Monday</h3>
      <h3 class="day">Tuesday</h3>
      <h3 class="day">Wednesday</h3>
      <h3 class="day">Thursday</h3>
      <h3 class="day">Friday</h3>
      <h3 class="day">Saturday</h3>
    </section>
  </body>
</html>

dashboard/templates/dashboard/base_dashboard.html
{% extends 'dashboard/base.html' %}
{% block title%}TaskManager Login{% endblock %}
{% load static %}
{% block styling %}
<link rel="stylesheet" href="{% static 'dashboard/css/dashboard.css' %}" type="text/css" media="screen">
{% endblock %}
{% block content %}
<div class="info_box">
    <h1>Dashboard content goes here</h1>
</div>
{% endblock %}