TaskManager/urls.py
from django.contrib import admin
import debug_toolbar
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include(debug_toolbar.urls)),
    path(
        "taskmanager/",
        include(
            [
                path("schedules/", include("schedules.urls", namespace="schedules")),
                path("tasks/", include("taskEvents.urls", namespace="tasks")),
                path("dashboard/", include("dashboard.urls", namespace="dashboard")),
                path("reviews/", include("reviews.urls", namespace="reviews")),
                path("employees/", include("employees.urls", namespace="employees")),
                path("events/", include("events.urls", namespace="events")),
            ]
        ),
    ),
]

employees/urls.py
from django.urls import path
from . import views
from employees.views import *

app_name = "employees"
urlpatterns = [
    path("form/", EmployeeFormView.as_view(), name="form"),
    path("edit/<int:pk>", EmployeeFormView.as_view(), name="edit"),
    path("create/", EmployeeCreateView.as_view(), name="create"),
    path("list/", EmployeeListView.as_view(), name="list"),
    path("update/<int:pk>", EmployeeUpdateView.as_view(), name="update"),
    path("delete/<int:pk>", EmployeeDeleteView.as_view(), name="delete"),
]

events/urls.py
from django.urls import path
from events import views
from events.views import *

app_name = "events"
urlpatterns = [
    path("", views.calendar_view, name='index'),
    path("<day__gte>", views.calendar_view),
    path("list/", EventListView.as_view(), name='list'),
    path("form/", EventFormView.as_view(), name='form'),
    path("create/", EventCreateView.as_view(), name='create'),
    path("update/<int:pk>", EventUpdateView.as_view(), name='update'),
    path("update-event/<int:pk>", views.update_event, name='change'),
    path("delete/<int:pk>", views.delete_event, name='delete'),
]

employees/models.py
from django.db import models
from .validators import validate_employee_number

# Create your models here.

class Departments(models.Model):
    LocationType = models.TextChoices('LocationType', 'FoH BoH')
    location = models.CharField(blank=True, choices=LocationType.choices, max_length=20, null=True)
    created_at = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    updated_at = models.DateTimeField(blank=True, null=True, auto_now=True)

    class Meta:
        db_table = 'departments'

class Positions(models.Model):
    TITLES = (
        ("1", "Manager"),
        ("2", "Assistant Manager"),
        ("3", "Supervisor"),
        ("4", "Server"),
        ("5", "Busser"),
        ("6", "Bartender"),
        ("7", "Expo"),
        ("8", "Host"),
        ("9", "Barback"),
        ("20", "Chef"),
        ("21", "Sous Chef"),
        ("22", "Pantry"),
        ("23", "Line Cook"),
        ("24", "Grill Cook"),
        ("25", "Prep Cook"),
        ("26", "Fry Cook"),
        ("27", "Dishwasher"),
        )
    title = models.CharField(choices=TITLES, max_length=45, blank=True, null=True)
    created_at = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    updated_at = models.DateTimeField(blank=True, null=True, auto_now=True)
    department = models.ForeignKey(Departments, models.DO_NOTHING, blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'positions'

class Employees(models.Model):
    position = models.ForeignKey('Positions', models.DO_NOTHING)
    login_num = models.CharField(        
        verbose_name="Employee #",
        max_length=4,
        # unique=True,
        help_text="4 digit pin",
        validators=[validate_employee_number],
)
    username = models.CharField(max_length=45)
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    email = models.EmailField(max_length=45)
    phone = models.CharField(max_length=45)
    start_date = models.DateField()
    status = models.BooleanField(help_text='Check if active', default=True, blank=False, null=False)
    created_at = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    updated_at = models.DateTimeField(blank=True, null=True, auto_now=True)

    def __str__(self):
        return self.first_name + " " + self.last_name

    class Meta:
        db_table = 'employees'

employees/forms.py
from django.forms import ModelForm
from employees.models import Departments, Employees, Departments
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError


# Create the form class. 


class EmployeeForm(ModelForm):
    # error_css_class = "error"
    class Meta:
        model = Employees
        fields = "__all__"

    def clean_login_num(self):
        login_num = self.cleaned_data.get("login_num")
        if len(login_num) < 4:
            raise ValidationError(_("Invalid ID Number."))
        else:
            try:
                login_num = int(login_num)
            except ValueError:
                raise ValidationError(_("Invalid ID Number."))
        return login_num


class DepartmentForm(ModelForm):
    class Meta:
        model = Departments
        fields = "__all__"

employees/views.py
from django.shortcuts import (
    render,
    redirect,
)
from django.contrib import messages
from .forms import EmployeeForm
from .models import Employees
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView, FormView
from django.urls import reverse_lazy

# Create your views here.

class EmployeeListView(ListView):
    """Shows a list of all employees in a table"""
    model = Employees


class ActiveEmployeeListView(ListView):
    """Shows a list of all Active employees in a table"""
    model = Employees
    queryset = Employees.objects.filter(status=1)

class EmployeeFormView(FormView):
    """New employee form """
    template_name = 'employees/employees_form.html'
    form_class = EmployeeForm
    model = Employees
    

class EmployeeCreateView(CreateView):
    model = Employees
    fields = '__all__'
    success_url = reverse_lazy('employees:list')

class EmployeeUpdateView(UpdateView):
    
    template_name = 'employees/employees_update.html'
    model = Employees
    fields = '__all__'
    success_url = reverse_lazy('employees:list')
    
class EmployeeDeleteView(DeleteView):
    model = Employees
    fields = '__all__'
    success_url = reverse_lazy('employees:list')

employees/templates/employees/base_createEmployee.html
{% extends 'dashboard/base.html' %}
{% block title%}View Employee{% endblock %}
{% load static %}
{% block styling %}
<link rel="stylesheet" href="{% static 'employees/css/editEmployees.css' %}" type="text/css" media="screen">
<script src="{% static 'employees/js/editEmployees.js' %}" type="text/javascript"></script>
{% endblock %}
{% block content %}

<div class="content">
    <div class="newForm">
        <form action="{% url 'employees:create' %}" method="POST">
            <h3 class="box_title">Create New Employee</h3>
            {% csrf_token %}
            {{ employeeForm }}<hr>
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
</div>
{% endblock %}

employees/templates/employees/base_employees.html
{% extends 'dashboard/base.html' %} {% block title%}Employees{% endblock %}
{%load static %} {% block styling %}
<link
  rel="stylesheet"
  href="{% static 'employees/css/base_employees.css' %}"
  type="text/css"
  media="screen"
/>
<!-- <script
  src="{% static 'employees/js/base_employees.js' %}"
  type="text/javascript"
></script> -->
{% endblock %} {% block content %}
<div class="content">
  <table id="employee-table">
    <thead>
      <th>Employee #</th>
      <th>Username</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Start Date</th>
      <th>Action</th>
    </thead>
    {% for employee in employeeList %}
    <tr>
      <td>{{ employee.login_num }}</td>
      <td>{{ employee.username|capfirst }}</td>
      <td>{{ employee.first_name|capfirst }}</td>
      <td>{{ employee.last_name|capfirst }}</td>
      <td>{{ employee.email }}</td>
      <td>{{ employee.phone }}</td>
      <td>{{ employee.start_date }}</td>
      <td id="action-link"><a href="{% url 'employees:update' employee.pk %}">Edit Info</a></td>
    </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}

employees/templates/employees/employees_form.html
{% extends 'dashboard/base.html' %}
{% block title%}View Employee{% endblock %}
{% load static %}
{% block styling %}
<link rel="stylesheet" href="{% static 'employees/css/employees_form.css' %}" type="text/css" media="screen">
<script src="{% static 'employees/js/employees_form.js' %}" type="text/javascript"></script>
{% endblock %}
{% block content %}
<h3 class="section_title">Create New Employee</h3>
<div class="content">
    <div class="newForm">
        <form action="{% url 'employees:create' %}" method="POST">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
</div>
{% endblock %}

employees/templates/employees/employees_list.html
{% extends 'dashboard/base.html' %} {% block title%}Employee List{% endblock %}
{%load static %} {% block styling %}

{% endblock %} {% block content %}
<div class="content">
  <table id="employees-table">
    <thead>
      <th>Employee #</th>
      <th>Username</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Start Date</th>
      <th>Action</th>
    </thead>
    {% for employee in object_list %}
    <tr>
      <td>{{ employee.login_num }}</td>
      <td>{{ employee.username|capfirst }}</td>
      <td>{{ employee.first_name|capfirst }}</td>
      <td>{{ employee.last_name|capfirst }}</td>
      <td>{{ employee.email }}</td>
      <td>{{ employee.phone }}</td>
      <td>{{ employee.start_date }}</td>
      <td id="action-link"><a href="{% url 'employees:edit' employee.pk %}">Edit Info</a></td>
    </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}

employees/templates/employees/employees_update.html
{% extends 'dashboard/base.html' %}
{% block title%}View Employee{% endblock %}
{% load static %}
{% block styling %}
<link rel="stylesheet" href="{% static 'employees/css/employees_form.css' %}" type="text/css" media="screen">
<script src="{% static 'employees/js/employees_form.js' %}" type="text/javascript"></script>
{% endblock %}
{% block content %}
    <h3 class="section_title">Update Existing Employee</h3>
    <div class="content">
        <div class="employee_form">
            <form action="{% url 'employees:update' employees.pk %}">{% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-secondary">Update</button>
                <a href="{% url 'employees:delete' employee.pk %}" class="btn btn-warning" >Delete</a>
            </form>
        </div>
    </div>
{% endblock %}