TaskManager/urls.py
from django.contrib import admin
import debug_toolbar
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include(debug_toolbar.urls)),
    path(
        "taskmanager/",
        include(
            [
                path("schedules/", include("schedules.urls", namespace="schedules")),
                path("tasks/", include("taskEvents.urls", namespace="tasks")),
                path("dashboard/", include("dashboard.urls", namespace="dashboard")),
                path("reviews/", include("reviews.urls", namespace="reviews")),
                path("employees/", include("employees.urls", namespace="employees")),
                path("events/", include("events.urls", namespace="events")),
            ]
        ),
    ),
]

events/urls.py
from django.urls import path
from events import views
from events.views import *

app_name = "events"
urlpatterns = [
    path("", views.calendar_view, name='index'),
    path("<day__gte>", views.calendar_view),
    path("list/", EventListView.as_view(), name='list'),
    path("form/", EventFormView.as_view(), name='form'),
    path("create/", EventCreateView.as_view(), name='create'),
    path("update/<int:pk>", EventUpdateView.as_view(), name='update'),
    path("update-event/<int:pk>", views.update_event, name='change'),
    path("delete/<int:pk>", views.delete_event, name='delete'),
]

schedules/urls.py
from django.urls import path
from schedules import views
from schedules.views import *

app_name = "schedules"
urlpatterns = [
    path("list/", ShiftListView.as_view(), name='list'),
    path("create/", views.schedule_form, name='create'),
    # path("select/<int:date>", views.schedule_select, name='select-schedule'),
    path("update/<int:pk>", ShiftUpdateView.as_view(), name='update'),
    path("delete/<int:pk>", views.shift_delete, name='delete'),
    path("create-schedule", views.create_schedule, name='create-schedule'),

    
]

schedules/models.py
from django.db import models
from employees.models import Positions
from datetime import date# Create your models here.

class Shifts(models.Model):
    date = models.ForeignKey("Schedule", models.DO_NOTHING)
    HOURS = (
        ("8", "8"),
        ("9", "9"),
        ("10", "10"),
        ("11", "11"),
        ("12", "12"),
        ("13", "13"),
        ("14", "14"),
        ("15", "15"),
        ("16", "16"),
        ("17", "17"),
        ("18", "18"),
        ("19", "19"),
        ("20", "20"),
        ("21", "21"),
        ("22", "22"),
    )
    in_time_hr = models.TimeField("In", choices=HOURS)
    out_time_hr = models.TimeField("Out", choices=HOURS)
    position = models.CharField(choices=Positions.TITLES, max_length=45, blank=True, null=True)
    created_at = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    updated_at = models.DateTimeField(blank=True, null=True, auto_now=True)


class Schedule(models.Model):
    date = models.DateField(default=date.today, unique=True)

schedules/forms.py
from django.forms import ModelForm
from schedules.models import Schedule, Shifts

class ScheduleForm(ModelForm):
    class Meta:
        model = Schedule
        fields = '__all__'

class ShiftForm(ModelForm):
    class Meta:
        model = Shifts
        fields = '__all__'

schedules/views.py
from django.http.request import HttpRequest
from django.shortcuts import render, redirect, reverse, HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from schedules.models import Shifts, Schedule
from django.urls import reverse_lazy
from schedules.forms import ScheduleForm, ShiftForm

from django.forms import inlineformset_factory, modelform_factory
# Create your views here.

class ShiftCreateView(CreateView):
    model = Shifts
    fields = '__all__'
    extra_context = { "shifts": Shifts.objects.all() }
    success_url="/taskmanager/schedules/list/"

class ShiftListView(ListView):
    model = Shifts

class ShiftUpdateView(UpdateView):
    model = Shifts
    fields = '__all__'
    success_url = "taskmanager/schedules/create"

def shift_delete(request, pk):
    s = Shifts.objects.get(pk=pk)
    s.delete()
    return redirect("schedues:list")

def schedule_select(request):
    schedules = Schedule.objects.all()
    scheduleForm = ScheduleForm()
    context = {
        "schedules": schedules,
        "scheduleForm": scheduleForm
    }
    return render(request, "schedules/shifts_list.html", context)

def schedule_form(request):
    shiftsForm = ShiftForm()
    scheduleForm = ScheduleForm()
    context = {
        "shiftsForm": shiftsForm,
        "scheduleForm": scheduleForm,
    }
    return render(request, "schedules/shifts_form.html", context)

def create_schedule(request):

    form = ScheduleForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect("select/")

    else:
        schedules = Schedule.objects.all()

        print(form.errors)
        context = { 
            "scheduleForm": form,
            "schedules": schedules,
            
        }
        return render(request, "schedules/shifts_list.html", context)

def select_schedule(request):
    shifts = Shifts.objects.filter(date_id= request.POST['date'])
    context = {
        "object_list": shifts
    }
    return render(request, "schedules/shifts_list.html", context)

schedules/templates/schedules/create_shift_footer.html
<div class="table-footer">
    <form id="shift-create-form" method="POST" action="{% url 'schedules:index' %}">{% csrf_token %}
        <select name="position" id="positionSelect">
            <option value="">Select Position</option>
            {% for position in positionList %}
                <option value="{{ position.id }}">{{ position.title }}</option>
            {% endfor %}
        </select>
        <a href="{% url 'reviews:index' %}" class="btn btn-primary" style="margin: 0px;">View All</a>
        <select name="employee" id="employeeSelect">
            <option value="">Select Employee</option>
            {% for employee in employeeList %}
                <option value="{{ employee.id }}">{{ employee.first_name }} {{ employee.last_name }}</option>
            {% endfor %}
        </select>
        <input class="btn btn-success" type="submit" value="Create">

    </form>
</div>

schedules/templates/schedules/schedule_selector.html
<div class="schedule-select-footer">
    <span>
            <select name="date">
                {% for date in schedules %}
                <form action="{% url 'schedules:select-schedule' date.id %}" method="GET">{% csrf_token %}
                    <option value="{{ date.id }}">{{ date.date }}</option>
                {% endfor %}
            </select>
        <button type="submit">Select</button>
        <h4>Select a date to edit schedule for</h4>
        </form>
    </span>
    <span>
        <form action="{% url 'schedules:create-schedule' %}" method="POST">{% csrf_token %}
            {{ scheduleForm.as_table }}
            <button type="submit">Create</button>
        <h4>Or add a date to create schedule for</h4>
        </form>
    </span>
</div>

schedules/templates/schedules/shifts_form.html
{% extends 'dashboard/base.html' %}
{% block title%}Schedules{% endblock %}
{% load static %}
{% block styling %}
{% endblock %}
{% block content %}
{% include "schedules/shifts_table.html" %}
<div class="shifts-create-footer">
    <div>
        <h4>1: Select which date to create schedule for</h4>
        <form action="{% url 'schedules:create-schedule' %}">{% csrf_token %}
            {{ scheduleForm.as_table}}
            <button type="submit">Select</button>
        </form>

    </div>
    <div class="form">
        {% if shifts.id %}
            <form class="eventForm" method="POST" action="{% url 'schedules:update' shifts.id %}">{% csrf_token %}
                {{ shiftsForm.as_table }}
                <button class="btn btn-success" type="submit">Update</button>
                <a href="{% url 'schedules:delete' shifts.id %}" class="btn btn-warning">Delete</a>
                </form>
            </form>
        {% else %}
            <form class="shiftForm" action="{% url 'schedules:create' %}" method="POST">{% csrf_token %}
                {{ shiftsForm.as_table }}
                <input class="btn btn-success" type="submit" value="Create">
            </form>
        {% endif %}
    </div>
</div>
{% endblock %}

schedules/templates/schedules/shifts_list.html
{% extends 'dashboard/base.html' %}
{% block title%}Schedule View{% endblock %}
{% load static %}
{% block styling %}
{% endblock %}
{% block content %}
<div class="shifts-content">
    <table id="schedules-table">
        <thead>
            <th>Day</th>
            <th>Position</th>
            <th>In</th>
            <th>Out</th>
            <th>Actions</th>
        </thead>
        {% for shift in object_list %}
        <tr>
            <td>{{ shift.day_of_week }}</td>
            <td>{{ shift.position }}</td>
            <td>{{ shift.in_time }}</td>
            <td>{{ shift.out_time }}</td>
            <td><a href="{% url 'schedules:update' shift.id %}">Update</a>&nbsp|&nbsp
                <a href="{% url 'schedules:delete' shift.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>
</div>
{% include "schedules/schedule_selector.html" %}
{% endblock %}

schedules/templates/schedules/shifts_table.html
<h3 class="section_title">Schedules List</h3> 
<div class="shifts-table-content">
    <table id="schedules-table">
        <thead>
            <th>Day</th>
            <th>Position</th>
            <th>In</th>
            <th>Out</th>
            <th>Actions</th>
        </thead>
        {% for shift in shifts %}
        <tr>
            <td>{{ shift.day_of_week }}</td>
            <td>{{ shift.position }}</td>
            <td>{{ shift.in_time }}</td>
            <td>{{ shift.out_time }}</td>
            <td><a href="{% url 'schedules:update' shift.id %}">Update</a>&nbsp|&nbsp
                <a href="{% url 'schedules:delete' shift.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>
</div>